import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

/*
Parts auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export function Model(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/boar.gltf");
    const { actions } = useAnimations(animations, group);

    //Auto-play animation. The name 'idle' comes from the Blender Project.
    useEffect(() => {
        actions.idle.play();
    });

    return (
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="boar">
            <primitive object={nodes.root} />
            <primitive object={nodes["MCH-front_thigh_ik_targetparentL"]} />
            <primitive object={nodes["MCH-front_thigh_ik_targetparentR"]} />
            <primitive object={nodes["MCH-thigh_ik_targetparentL"]} />
            <primitive object={nodes["MCH-thigh_ik_targetparentR"]} />
            <primitive object={nodes["MCH-torsoparent"]} />
            <primitive object={nodes["MCH-front_foot_ikparentL"]} />
            <primitive object={nodes["MCH-front_foot_ikparentR"]} />
            <primitive object={nodes["MCH-foot_ikparentL"]} />
            <primitive object={nodes["MCH-foot_ikparentR"]} />
            <skinnedMesh
              name="Boar"
              geometry={nodes.Boar.geometry}
              material={materials.Boar_MAT}
              skeleton={nodes.Boar.skeleton}
            />
            <skinnedMesh
              name="Plane"
              geometry={nodes.Plane.geometry}
              material={materials.Vine_MAT}
              skeleton={nodes.Plane.skeleton}
            />
          </group>
        </group>
      </group>
    );
  }
  

export default function Boar() {
    return (<Model 
      scale={[0.66,0.66,0.66]} 
      position={[-3,0,0]}/>);
}

useGLTF.preload("/boar.gltf");