import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from 'three'

/*
Parts auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export function Model(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/boar.gltf");
    const { actions } = useAnimations(animations, group);

    //Auto-play animation. The name 'idle' comes from the Blender Project.
    useEffect(() => {
        actions.idle.play();
    });

    //Used for Boar's hit detection
    //SkinnedMeshes are rendered on the GPU, so a regular mesh is required for proper mouse events.
    let hitboxGeometry = new THREE.BoxBufferGeometry(2, 3, 5);
    let hitboxMaterial = new THREE.MeshBasicMaterial({visible: false});

    return (
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="boar">
            <primitive object={nodes.root} />
            <primitive object={nodes["MCH-front_thigh_ik_targetparentL"]} />
            <primitive object={nodes["MCH-front_thigh_ik_targetparentR"]} />
            <primitive object={nodes["MCH-thigh_ik_targetparentL"]} />
            <primitive object={nodes["MCH-thigh_ik_targetparentR"]} />
            <primitive object={nodes["MCH-torsoparent"]} />
            <primitive object={nodes["MCH-front_foot_ikparentL"]} />
            <primitive object={nodes["MCH-front_foot_ikparentR"]} />
            <primitive object={nodes["MCH-foot_ikparentL"]} />
            <primitive object={nodes["MCH-foot_ikparentR"]} />

            <mesh geometry={hitboxGeometry} material={hitboxMaterial} position={[0,1.5,0]}
              onPointerEnter={(e) => {
                actions.idle.fadeOut(0.5);
                actions.rustle.reset().fadeIn(0.5).play()}}
              onPointerLeave={(e) => {
                actions.rustle.fadeOut(0.5);
                actions.idle.reset().fadeIn(0.5).play()}}>                                    
            </mesh>

            <skinnedMesh
              name="Boar"
              geometry={nodes.Boar.geometry}
              material={materials.Boar_MAT}
              skeleton={nodes.Boar.skeleton}
            />
            <skinnedMesh
              name="Plane"
              geometry={nodes.Plane.geometry}
              material={materials.Vine_MAT}
              skeleton={nodes.Plane.skeleton}
            />
          </group>
        </group>
      </group>
    );
  }
  

export default function Boar() {
    return (<Model 
      scale={[0.66,0.66,0.66]} 
      position={[-3,0,0]}/>);
}

useGLTF.preload("/boar.gltf");