/*
Parts auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from 'three'

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/flora-noanim.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.chill.setEffectiveTimeScale(0.3);
    actions.chill.reset().fadeIn(0.5).play();    
    });

  //Used for Flora's hit detection
  //SkinnedMeshes are rendered on the GPU, so a regular mesh is required for proper mouse events.
  let hitboxGeometry = new THREE.BoxBufferGeometry(1, 1.5, 1);
  let hitboxMaterial = new THREE.MeshBasicMaterial({visible: false});

  return (    
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="flora">
          <primitive object={nodes.root} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentL"]} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentR"]} />
          <primitive object={nodes["MCH-thigh_ik_targetparentL"]} />
          <primitive object={nodes["MCH-thigh_ik_targetparentR"]} />
          <primitive object={nodes["MCH-torsoparent"]} />
          <primitive object={nodes["MCH-forearm_ikparentL001"]} />
          <primitive object={nodes["MCH-forearm_ikparentR001"]} />
          <primitive object={nodes["MCH-foot_ikparentL"]} />
          <primitive object={nodes["MCH-foot_ikparentR"]} />
        
          <mesh geometry={hitboxGeometry} material={hitboxMaterial} position={[0,0.75,-0.3]}
            onPointerEnter={(e) => {
              actions.chill.stop();
              actions.wave.reset().fadeIn(0.1).play()}}
            onPointerLeave={(e) => {
              actions.wave.fadeOut(0.2);
              actions.chill.reset().fadeIn(0.3).play()}}>                                    
          </mesh>

          <skinnedMesh
            name="Rose"
            geometry={nodes.Rose.geometry}
            material={materials.Material}
            skeleton={nodes.Rose.skeleton}
            
          />
        </group>
      </group>
    </group>
  );
}
  
export default function Flora() {
    return (<Model 
      position={[-1,0,0]} 
      rotation={[0,-Math.PI/4,0]}
      />);
}

useGLTF.preload("/flora-noanim.gltf");