import React from "react";
import { useGLTF } from "@react-three/drei";

/*
Parts auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export function Model(props) {
  const { nodes, materials } = useGLTF("/grass.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}        
      />
    </group>
  );
}

export default function Ground() {
    return (<Model 
      scale={[3,3,3]} 
      position={[-2,0,0]}
      />);
}

useGLTF.preload("/grass.gltf");